#spring.datasource:
#  url: jdbc:h2:mem:camunda-db;DB_CLOSE_DELAY=-1;MVCC=TRUE;DB_CLOSE_ON_EXIT=FALSE
#  username: sa
#  password: sa
spring.h2.console.enabled: true
#spring.h2.console.path: /h2-console
camunda.bpm:
  admin-user:
    id: kermit
    password: superSecret
    firstName: Kermit
  filter:
    create: All tasks